name: Run Azure to Github Sync with PowerShell

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - run: |
          ./SyncAzuretoGithub.ps1 -GithubDestinationPAT ${{secrets.GITHUBDESTINATIONPAT}} -AzureSourcePAT ${{secrets.AZURESOURCEPAT}}
